#!/bin/bash
# Preserve identity and generate machine-local pager settings.
GIT_GENERATED="$HOME/.gitconfig.envup"

_git_write_generated() {
    local delta; delta="$(bin_path delta 2>/dev/null || true)"

    if [[ "${ENVUP_DRY_RUN:-0}" == 1 ]]; then
        if [[ -n "$delta" ]]; then log_info "[dry-run] would enable the delta pager in $GIT_GENERATED"
        else log_info "[dry-run] would write $GIT_GENERATED (delta not installed here)"; fi
        return 0
    fi

    {
        echo "# Generated by 'envup install git' — do not edit, it is rewritten"
        echo "# every install. Per-machine settings you want to keep belong in"
        echo "# modules/git/files/hosts/<hostname>.gitconfig (committed) or"
        echo "# ~/.gitconfig.local (private). Both are included after this file."
        if [[ -n "$delta" ]]; then
            printf '\n[pager]\n\tdiff = %s\n\tlog = %s\n\treflog = %s\n\tshow = %s\n' \
                   "$delta" "$delta" "$delta" "$delta"
            printf '\n[interactive]\n\tdiffFilter = %s --color-only\n' "$delta"
        fi
    } > "$GIT_GENERATED"

    if [[ -n "$delta" ]]; then
        log_success "delta found — enabled as git's pager"
    else
        log_info "delta not installed here; git keeps its default pager"
    fi
}

pre_install() {
    # Read identity before ~/.gitconfig is replaced by a managed link.
    _GIT_CARRY_NAME="$(git config --global user.name  2>/dev/null || true)"
    _GIT_CARRY_MAIL="$(git config --global user.email 2>/dev/null || true)"
    return 0
}

post_install() {
    _git_write_generated

    local cfg="$HOME/.gitconfig.local"
    if [[ "${ENVUP_DRY_RUN:-0}" == 1 ]]; then
        log_info "[dry-run] would ensure $cfg exists"; return 0
    fi
    [[ -e "$cfg" ]] && return 0

    cat > "$cfg" <<EOF
# Per-machine git identity — NOT in the repo. Loaded last via [include].
[user]
    name  = ${_GIT_CARRY_NAME:-YOUR NAME}
    email = ${_GIT_CARRY_MAIL:-your.email@example.com}
EOF
    if [[ -n "$_GIT_CARRY_NAME" && -n "$_GIT_CARRY_MAIL" ]]; then
        log_success "created $cfg (kept the identity this machine already had)"
    else
        log_warn "created $cfg — set a real name/email or 'git commit' will refuse to run"
        log_hint "edit it: \$EDITOR $cfg"
    fi
}

post_uninstall() {
    if [[ "${ENVUP_DRY_RUN:-0}" == 1 ]]; then
        log_info "[dry-run] would remove $GIT_GENERATED"
    else
        rm -f "$GIT_GENERATED"
    fi
    # shellcheck disable=SC2088  # literal ~ is display text, not a path to expand
    log_info "~/.gitconfig.local (your identity) kept"
    return 0
}
