#!/usr/bin/env bats
# Checking that a download is the file the release says it is.
#
# The threat this addresses is not a compromised upstream — a checksum published
# in the same release and fetched over the same link cannot tell you about that.
# It is the download that arrived wrong: the corporate proxy that answers 200
# with a login page, the transfer cut off when the link dropped, the mirror a
# week behind. Each of those installs cleanly today and is discovered somewhere
# else entirely, so the whole value is in refusing them at the door.

load '../test_helper'

setup() {
    common_setup
    # shellcheck source=/dev/null
    source "$REPO_ROOT/lib/providers/github_release.sh"
    NAME="testmod"
    FILE="$TEST_TMP/payload.tar.gz"
    printf 'the real thing\n' > "$FILE"
    GOOD="$(sha256sum "$FILE" | awk '{print $1}')"
    BAD="$(printf '%064d' 0)"
}
teardown() { common_teardown; }

# ---- computing a digest --------------------------------------------------

@test "net_digest agrees with sha256sum" {
    run net_digest "$FILE" 256
    [ "$status" -eq 0 ]
    [ "$output" = "$GOOD" ]
}

@test "net_digest does sha512 too" {
    run net_digest "$FILE" 512
    [ "$status" -eq 0 ]
    [ "$output" = "$(sha512sum "$FILE" | awk '{print $1}')" ]
}

@test "openssl gives the same answer as coreutils" {
    # Its output puts the digest last instead of first — the parser reads the
    # digest by its shape for exactly this reason.
    command -v openssl >/dev/null || skip "no openssl"
    isolate_path openssl
    run net_digest "$FILE" 256
    [ "$status" -eq 0 ]
    [ "$output" = "$GOOD" ]
}

@test "shasum is called the way macOS wants it" {
    # No coreutils on a stock Mac; shasum is the one that is always there, and
    # it needs -a 256 rather than a command name that carries the algorithm.
    stub_bin shasum <<'EOF'
#!/bin/bash
printf '%s\n' "$*" > "$SHASUM_ARGS"
printf '%s  %s\n' "0000000000000000000000000000000000000000000000000000000000000000" "$3"
EOF
    export SHASUM_ARGS="$TEST_TMP/shasum-args"
    isolate_path                       # coreutils goes; the stub survives
    rm -f "$STUB_BIN/openssl"
    run net_digest "$FILE" 256
    [ "$status" -eq 0 ]
    [[ "$(cat "$SHASUM_ARGS")" == "-a 256 "* ]]
}

@test "a machine with no digest tool says so instead of guessing" {
    isolate_path                       # no sha256sum, no shasum, no openssl
    run net_digest "$FILE" 256
    [ "$status" -ne 0 ]
}

# ---- reading a checksum file ---------------------------------------------
#
# Three layouts, all of them in current use by upstreams envup installs.

sums() { printf '%s' "$TEST_TMP/sums"; }

@test "GNU format: '<hex>  <name>'" {
    printf '%s  payload.tar.gz\n' "$GOOD" > "$(sums)"
    run net_sum_lookup "$(sums)" payload.tar.gz
    [ "$output" = "$GOOD" ]
}

@test "GNU binary format: '<hex> *<name>'" {
    printf '%s *payload.tar.gz\n' "$GOOD" > "$(sums)"
    run net_sum_lookup "$(sums)" payload.tar.gz
    [ "$output" = "$GOOD" ]
}

@test "BSD format: 'SHA256 (<name>) = <hex>'" {
    printf 'SHA256 (payload.tar.gz) = %s\n' "$GOOD" > "$(sums)"
    run net_sum_lookup "$(sums)" payload.tar.gz
    [ "$output" = "$GOOD" ]
}

@test "a sidecar holding nothing but the number" {
    # <asset>.sha256 files often carry no name at all, because there is only
    # ever one thing they could be about.
    printf '%s\n' "$GOOD" > "$(sums)"
    run net_sum_lookup "$(sums)" payload.tar.gz
    [ "$output" = "$GOOD" ]
}

@test "an uppercase digest is still the same digest" {
    printf '%s  payload.tar.gz\n' "$(tr 'a-f' 'A-F' <<<"$GOOD")" > "$(sums)"
    run net_sum_lookup "$(sums)" payload.tar.gz
    [ "$output" = "$GOOD" ]
}

@test "a path in the manifest is matched by its basename" {
    printf '%s  dist/payload.tar.gz\n' "$GOOD" > "$(sums)"
    run net_sum_lookup "$(sums)" payload.tar.gz
    [ "$output" = "$GOOD" ]
}

@test "the right line is picked out of a whole-release manifest" {
    # This is the one that matters: a checksums.txt lists every asset, and
    # taking the first line would validate the file against the Windows build.
    {
        printf '%s  payload-windows.zip\n' "$BAD"
        printf '%s  payload.tar.gz\n'      "$GOOD"
        printf '%s  payload-darwin.tar.gz\n' "$BAD"
    } > "$(sums)"
    run net_sum_lookup "$(sums)" payload.tar.gz
    [ "$output" = "$GOOD" ]
}

@test "a name that is not listed is not silently the last one" {
    printf '%s  something-else.tar.gz\n' "$GOOD" > "$(sums)"
    run net_sum_lookup "$(sums)" payload.tar.gz
    [ "$status" -ne 0 ]
    [ -z "$output" ]
}

@test "comments and blank lines are not digests" {
    printf '# generated by goreleaser\n\n%s  payload.tar.gz\n' "$GOOD" > "$(sums)"
    run net_sum_lookup "$(sums)" payload.tar.gz
    [ "$output" = "$GOOD" ]
}

@test "a last line with no newline is still read" {
    printf '%s  payload.tar.gz' "$GOOD" > "$(sums)"
    run net_sum_lookup "$(sums)" payload.tar.gz
    [ "$output" = "$GOOD" ]
}

@test "sha1 is not accepted as an answer" {
    # eza ships a SHA1SUMS alongside its sha256 files. 40 hex characters is not
    # a digest we are willing to trust a binary to.
    printf '%s  payload.tar.gz\n' "$(printf 'a%.0s' {1..40})" > "$(sums)"
    run net_sum_lookup "$(sums)" payload.tar.gz
    [ "$status" -ne 0 ]
}

# ---- the three-way verdict -----------------------------------------------

@test "a matching file passes" {
    printf '%s  payload.tar.gz\n' "$GOOD" > "$(sums)"
    run net_verify_file "$FILE" "$(sums)"
    [ "$status" -eq 0 ]
}

@test "a file that does not match fails, and both digests are printed" {
    # Without them the message is unactionable — you cannot tell a truncated
    # download from the wrong asset entirely.
    printf '%s  payload.tar.gz\n' "$BAD" > "$(sums)"
    run net_verify_file "$FILE" "$(sums)"
    [ "$status" -eq 1 ]
    [[ "$output" == *"$BAD"* ]]
    [[ "$output" == *"$GOOD"* ]]
}

@test "nothing to compare against is its own answer, not a pass and not a fail" {
    printf '%s  other.tar.gz\n' "$GOOD" > "$(sums)"
    run net_verify_file "$FILE" "$(sums)"
    [ "$status" -eq 2 ]
}

@test "no tool to compute a digest is also 'cannot tell'" {
    printf '%s  payload.tar.gz\n' "$GOOD" > "$(sums)"
    isolate_path
    run net_verify_file "$FILE" "$(sums)"
    [ "$status" -eq 2 ]
}

@test "a sha512 line is checked with sha512" {
    # The algorithm comes from the length of what was published, because the
    # file name rarely says.
    printf '%s  payload.tar.gz\n' "$(sha512sum "$FILE" | awk '{print $1}')" > "$(sums)"
    run net_verify_file "$FILE" "$(sums)"
    [ "$status" -eq 0 ]
}

# ---- finding the checksum in a release -----------------------------------

ASSET="https://github.com/o/r/releases/download/v1/tool-x86_64-linux.tar.gz"

@test "the sidecar wins over the release-wide manifest" {
    # It cannot be about a different asset, so there is nothing to get wrong.
    run _ghr_sum_url "$ASSET" \
        "https://github.com/o/r/releases/download/v1/checksums.txt" \
        "$ASSET" \
        "$ASSET.sha256"
    [ "$output" = "$ASSET.sha256" ]
}

@test "goreleaser's checksums.txt is found" {
    run _ghr_sum_url "$ASSET" "$ASSET" \
        "https://github.com/o/r/releases/download/v1/checksums.txt"
    [[ "$output" == *checksums.txt ]]
}

@test "fzf's <name>_<version>_checksums.txt is found" {
    run _ghr_sum_url "$ASSET" "$ASSET" \
        "https://github.com/o/r/releases/download/v1/fzf_0.74.2_checksums.txt"
    [[ "$output" == *fzf_0.74.2_checksums.txt ]]
}

@test "neovim's shasum.txt is found" {
    run _ghr_sum_url "$ASSET" "$ASSET" \
        "https://github.com/o/r/releases/download/v1/shasum.txt"
    [[ "$output" == *shasum.txt ]]
}

@test "a release that publishes nothing reports nothing" {
    run _ghr_sum_url "$ASSET" "$ASSET" \
        "https://github.com/o/r/releases/download/v1/tool-aarch64-linux.tar.gz"
    [ "$status" -ne 0 ]
    [ -z "$output" ]
}

@test "another asset's sidecar is not mistaken for ours" {
    run _ghr_sum_url "$ASSET" "$ASSET" \
        "https://github.com/o/r/releases/download/v1/tool-aarch64-linux.tar.gz.sha256"
    [ "$status" -ne 0 ]
}

# ---- policy --------------------------------------------------------------

@test "an upstream with no checksums still installs" {
    # fd, bat and delta publish none. Refusing them by default would trade a
    # real capability for a guarantee we cannot offer anyway.
    run _ghr_unverified "this release publishes no checksums"
    [ "$status" -eq 0 ]
}

@test "ENVUP_REQUIRE_CHECKSUM=1 turns that into a refusal" {
    # For the case the default cannot cover: ENVUP_GH_MIRROR pointed at a proxy
    # you do not run.
    ENVUP_REQUIRE_CHECKSUM=1 run _ghr_unverified "this release publishes no checksums"
    [ "$status" -ne 0 ]
    [[ "$output" == *"ENVUP_REQUIRE_CHECKSUM"* ]]
}

# ---- the provider's own step ---------------------------------------------
#
# net_fetch is replaced rather than stubbed on PATH: it is a shell function, and
# what we want to control is which bytes come back for the sums URL.

fake_fetch() {
    net_fetch() {
        local url="$1" dest="$2"
        [[ -r "$TEST_TMP/served" ]] || return 1
        cp "$TEST_TMP/served" "$dest"
    }
}

@test "the download is checked before anything is unpacked" {
    printf '%s  payload.tar.gz\n' "$GOOD" > "$TEST_TMP/served"
    fake_fetch
    run _ghr_check "$FILE" \
        "https://github.com/o/r/releases/download/v1/payload.tar.gz" "$TEST_TMP" \
        "https://github.com/o/r/releases/download/v1/payload.tar.gz" \
        "https://github.com/o/r/releases/download/v1/checksums.txt"
    [ "$status" -eq 0 ]
}

@test "a file that is not what the release says is refused" {
    printf '%s  payload.tar.gz\n' "$BAD" > "$TEST_TMP/served"
    fake_fetch
    run _ghr_check "$FILE" \
        "https://github.com/o/r/releases/download/v1/payload.tar.gz" "$TEST_TMP" \
        "https://github.com/o/r/releases/download/v1/payload.tar.gz" \
        "https://github.com/o/r/releases/download/v1/checksums.txt"
    [ "$status" -eq 1 ]
}

@test "a checksum file that will not download is not a failed install" {
    rm -f "$TEST_TMP/served"
    fake_fetch
    run _ghr_check "$FILE" \
        "https://github.com/o/r/releases/download/v1/payload.tar.gz" "$TEST_TMP" \
        "https://github.com/o/r/releases/download/v1/payload.tar.gz" \
        "https://github.com/o/r/releases/download/v1/checksums.txt"
    [ "$status" -eq 0 ]
}

@test "…unless you asked for checksums to be mandatory" {
    rm -f "$TEST_TMP/served"
    fake_fetch
    ENVUP_REQUIRE_CHECKSUM=1 run _ghr_check "$FILE" \
        "https://github.com/o/r/releases/download/v1/payload.tar.gz" "$TEST_TMP" \
        "https://github.com/o/r/releases/download/v1/payload.tar.gz" \
        "https://github.com/o/r/releases/download/v1/checksums.txt"
    [ "$status" -ne 0 ]
}

@test "the query string on a download URL is not part of the file name" {
    # Mirrors add one. Looking up 'payload.tar.gz?token=...' finds nothing in
    # the manifest, and the check quietly becomes a no-op — which is invisible
    # by default, since a missing digest is allowed. Hence the strict mode here:
    # it is the only setting under which that no-op is distinguishable from a
    # real pass.
    printf '%s  payload.tar.gz\n' "$GOOD" > "$TEST_TMP/served"
    fake_fetch
    ENVUP_REQUIRE_CHECKSUM=1 run _ghr_check "$FILE" \
        "https://github.com/o/r/releases/download/v1/payload.tar.gz?token=abc" "$TEST_TMP" \
        "https://github.com/o/r/releases/download/v1/checksums.txt"
    [ "$status" -eq 0 ]
}
