#!/usr/bin/env bats
# The shared .gitconfig is committed once and read on every machine, so anything
# in it that names a program is a bet that the program is there. It kept losing
# those bets: core.editor = nvim on a box with no nvim breaks `git commit`, and
# an interactive.diffFilter naming delta breaks `git add -p`. Machine-specific
# facts now come from a layer that knows which machine it is on.

load '../test_helper'

setup() {
    common_setup
    GITCFG="$REPO_ROOT/modules/git/files/.gitconfig"
    GENERATED="$HOME/.gitconfig.envup"
    source "$REPO_ROOT/modules/git/meta.sh"
    source "$REPO_ROOT/modules/git/hooks.sh"
}
teardown() { common_teardown; }

@test "the shared config names no editor" {
    # A committed guess is wrong on some machine, and it is wrong at exactly the
    # moment you least want it: mid-commit. 30-env.zsh picks from what exists.
    ! grep -Eq '^[[:space:]]*editor[[:space:]]*=' "$GITCFG"
}

@test "the shared config names no diff or merge tool" {
    # vimdiff on a machine with neither vim nor nvim turns `git mergetool` into
    # an error at the worst possible time.
    ! grep -Eq '^[[:space:]]*(tool|guitool)[[:space:]]*=' "$GITCFG"
}

@test "the shared config names no pager binary" {
    # delta belongs in the generated layer, where its absence is a fact rather
    # than a promise. A .gitconfig that pipes every diff into a missing binary
    # is a git that cannot show you a diff.
    ! grep -Eq '^[[:space:]]*(diffFilter|pager|diff|log|reflog|show)[[:space:]]*=.*delta' "$GITCFG"
}

@test "conflictstyle and colorMoved stay — they need no binary" {
    grep -q 'conflictstyle = diff3' "$GITCFG"
    grep -q 'colorMoved = default' "$GITCFG"
}

# ---- the generated layer -------------------------------------------------

@test "delta is enabled when it is actually installed" {
    stub_bin delta <<'EOF'
#!/bin/bash
echo "delta 0.17.0"
EOF
    run _git_write_generated
    [ "$status" -eq 0 ]
    grep -q '\[pager\]' "$GENERATED"
    grep -q 'diff = .*delta' "$GENERATED"
    grep -q 'diffFilter = .*delta --color-only' "$GENERATED"
}

@test "the generated file records an absolute path, not a bare name" {
    # git runs the pager through the shell, but a login shell's PATH is not the
    # PATH envup installed under — ~/.local/bin in particular. Resolving now
    # means the setting still works from a GUI client or a cron job.
    stub_bin delta <<'EOF'
#!/bin/bash
echo "delta 0.17.0"
EOF
    _git_write_generated
    grep -Eq 'diff = /' "$GENERATED"
}

@test "no delta means no pager section at all" {
    isolate_path                       # delta is not in the minimum set
    run _git_write_generated
    [ "$status" -eq 0 ]
    [ -f "$GENERATED" ]                # written, so a stale one is overwritten
    ! grep -q 'pager' "$GENERATED"
    ! grep -q 'diffFilter' "$GENERATED"
}

@test "a machine that loses delta loses the setting too" {
    # The file is rewritten every install, not appended to. Otherwise removing
    # delta leaves a .gitconfig.envup that breaks every diff.
    stub_bin delta <<'EOF'
#!/bin/bash
echo "delta 0.17.0"
EOF
    _git_write_generated
    grep -q 'delta' "$GENERATED"

    rm -f "$STUB_BIN/delta"
    isolate_path
    _git_write_generated
    ! grep -q 'delta' "$GENERATED"
}

@test "the generated file says not to edit it, and where to go instead" {
    isolate_path
    _git_write_generated
    grep -q 'Generated by' "$GENERATED"
    grep -q 'hosts/' "$GENERATED"
    grep -q 'gitconfig.local' "$GENERATED"
}

@test "the generated file is valid git config" {
    stub_bin delta <<'EOF'
#!/bin/bash
echo "delta 0.17.0"
EOF
    _git_write_generated
    run git config --file "$GENERATED" --list
    [ "$status" -eq 0 ]
    [[ "$output" == *"pager.diff="* ]]
}

@test "dry-run writes nothing" {
    stub_bin delta <<'EOF'
#!/bin/bash
echo "delta 0.17.0"
EOF
    ENVUP_DRY_RUN=1 run _git_write_generated
    [ "$status" -eq 0 ]
    [ ! -e "$GENERATED" ]
    [[ "$output" == *"dry-run"* ]]
}

@test "uninstall takes the generated file with it" {
    # envup wrote it, so envup owns it; leaving it behind would keep pointing a
    # removed setup's pager at a binary this machine may not keep.
    isolate_path
    _git_write_generated
    [ -f "$GENERATED" ]
    run post_uninstall
    [ "$status" -eq 0 ]
    [ ! -e "$GENERATED" ]
}

@test "uninstall leaves the layers it did not write" {
    printf '[user]\n\temail = me@example.com\n' > "$HOME/.gitconfig.local"
    printf '[core]\n\tpager = cat\n' > "$HOME/.gitconfig.host"
    post_uninstall
    [ -f "$HOME/.gitconfig.local" ]
    [ -f "$HOME/.gitconfig.host" ]
}

@test "dry-run uninstall removes nothing" {
    isolate_path
    _git_write_generated
    ENVUP_DRY_RUN=1 run post_uninstall
    [ -f "$GENERATED" ]
}

@test "install writes the generated layer before anything else needs it" {
    stub_bin delta <<'EOF'
#!/bin/bash
echo "delta 0.17.0"
EOF
    run post_install
    [ "$status" -eq 0 ]
    [ -f "$GENERATED" ]
}

@test "the generated layer is the weakest of the three" {
    # envup's detection is a default; a host file and a private file are
    # decisions, and both must be able to overrule it.
    local h="$TEST_TMP/githome"; mkdir -p "$h"
    cp "$GITCFG" "$h/.gitconfig"
    printf '[pager]\n\tdiff = delta\n' > "$h/.gitconfig.envup"
    printf '[pager]\n\tdiff = less\n'  > "$h/.gitconfig.host"

    run env HOME="$h" XDG_CONFIG_HOME="$h/xdg" git config --get pager.diff
    [ "$status" -eq 0 ]
    [ "$output" = "less" ]
}
